name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    name: Deploy to symbient.be
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/deploy/projects/lemmy
            git pull origin main
            bash /home/deploy/scripts/deploy.sh

      - name: Deployment Status
        if: success()
        run: echo "✅ Deployment successful to internet.symbient.be"

      - name: Deployment Failed
        if: failure()
        run: |
          echo "❌ Deployment failed"
          exit 1
